from django.contrib.auth.models import User
from django.db.models import Model, ForeignKey, ManyToManyField
from django.db.models import NullBooleanField, CharField, DateField, TimeField, EmailField, IntegerField, TextField

# Create your models here.
class App(Model):
    acronym                              = CharField(max_length=128)
    acronym_previous                     = CharField(max_length=128, blank=True, null=True)
    application_type                     = CharField(max_length=128, blank=True, null=True) # M2M
    application_type_previous            = CharField(max_length=128, blank=True, null=True) # M2M
    architecture_type                    = CharField(max_length=128, blank=True, null=True)
    architecture_type_previous           = CharField(max_length=128, blank=True, null=True)
    comments                             = TextField(max_length=1024, blank=True, null=True)
    compliance_508                       = CharField(max_length=128, blank=True, null=True)
    compliance_508_previous              = CharField(max_length=128, blank=True, null=True)
    data_impact_type                     = CharField(max_length=128, blank=True, null=True)
    data_impact_type_previous            = CharField(max_length=128, blank=True, null=True)
    dbms_names_and_version               = CharField(max_length=128, blank=True, null=True)
    dbms_names_and_version_previous      = CharField(max_length=128, blank=True, null=True)
    description                          = TextField(max_length=1024, blank=True, null=True)
    description_previous                 = TextField(max_length=1024, blank=True, null=True)
    fips_information_category            = CharField(max_length=128, blank=True, null=True)
    fips_information_category_previous   = CharField(max_length=128, blank=True, null=True)
    hitss_supported                      = CharField(max_length=128, blank=True, null=True)
    hitss_supported_previous             = CharField(max_length=128, blank=True, null=True)
    interface_acronym                    = CharField(max_length=128, blank=True, null=True)
    interface_acronym_previous           = CharField(max_length=128, blank=True, null=True)
    interface_direction                  = CharField(max_length=128, blank=True, null=True)
    interface_direction_previous         = CharField(max_length=128, blank=True, null=True)
    interface_method                     = CharField(max_length=128, blank=True, null=True)
    interface_method_previous            = CharField(max_length=128, blank=True, null=True)
    internal_or_external_system          = CharField(max_length=128, blank=True, null=True)
    internal_or_external_system_previous = CharField(max_length=128, blank=True, null=True)
    name                                 = CharField(max_length=128, blank=True, null=True)
    name_previous                        = CharField(max_length=128, blank=True, null=True)
    network_services_used                = CharField(max_length=128, blank=True, null=True)
    network_services_used_previous       = CharField(max_length=128, blank=True, null=True)
    number_of_users                      = CharField(max_length=128, blank=True, null=True)
    number_of_users_previous             = CharField(max_length=128, blank=True, null=True)
    project_manager_name                 = CharField(max_length=128, blank=True, null=True)
    project_manager_name_previous        = CharField(max_length=128, blank=True, null=True)
    security_plan_number                 = CharField(max_length=128, blank=True, null=True)
    security_plan_number_previous        = CharField(max_length=128, blank=True, null=True)
    servers_application                  = CharField(max_length=128, blank=True, null=True)
    servers_application_previous         = CharField(max_length=128, blank=True, null=True)
    servers_database                     = CharField(max_length=128, blank=True, null=True)
    servers_database_previous            = CharField(max_length=128, blank=True, null=True)
    servers_location                     = CharField(max_length=128, blank=True, null=True)
    servers_location_previous            = CharField(max_length=128, blank=True, null=True)
    servers_report                       = CharField(max_length=128, blank=True, null=True)
    servers_report_previous              = CharField(max_length=128, blank=True, null=True)
    service_request_classs               = CharField(max_length=128, blank=True, null=True)
    service_request_classs_previous      = CharField(max_length=128, blank=True, null=True)
    service_request_numbers              = CharField(max_length=128, blank=True, null=True)
    service_request_numbers_previous     = CharField(max_length=128, blank=True, null=True)
    software_class                       = CharField(max_length=128, blank=True, null=True)
    software_class_previous              = CharField(max_length=128, blank=True, null=True)
    software_names_and_versions          = CharField(max_length=128, blank=True, null=True)
    software_names_and_versions_previous = CharField(max_length=128, blank=True, null=True)
    support_class                        = CharField(max_length=128, blank=True, null=True)
    support_class_previous               = CharField(max_length=128, blank=True, null=True)
    url_link                             = CharField(max_length=128, blank=True, null=True)
    url_link_previous                    = CharField(max_length=128, blank=True, null=True)
    user_groups                          = CharField(max_length=128, blank=True, null=True)
    user_groups_previous                 = CharField(max_length=128, blank=True, null=True)
    version_change_description           = CharField(max_length=128, blank=True, null=True)
    version_change_description_previous  = CharField(max_length=128, blank=True, null=True)
    version_number                       = CharField(max_length=128, blank=True, null=True)
    version_number_previous              = CharField(max_length=128, blank=True, null=True)
    version_status                       = CharField(max_length=128, blank=True, null=True)
    version_status_previous              = CharField(max_length=128, blank=True, null=True)

    def __unicode__(self):
        return u'%s-%s' % (self.acronym, self.version_number)
